### ISSUE TITLE
Not Online

### ISSUE THREAD

**Issue by Keri-Lynn** [Keri-Lynn/me-oh-my-html#1]
@thomasjbradley

Saying I am not online.

**Comment by thomasjbradley** [comment]
Inside Markbot, I’d like you to sign out—from the menu.
Mac: `Markbot > Sign Out`
Win: `File > Sign Out`

Then sign back into Markbot.
**Make sure you spell your GitHub username as exactly: `Keri-Lynn`**

**Comment by Keri-Lynn** [comment]
@charlie-quinn @thomasjbradley

Done but not online.

![Screenshot (656)](https://user-images.githubusercontent.com/43151336/67522993-c2bbab00-f67b-11e9-85e0-45d528a25f0e.png)

**Comment by thomasjbradley** [comment]
Same problem. Wrong GitHub username.

**Comment by Keri-Lynn** [comment]
@thomasjbradley 

Awesome!!!  Thanks a bunch.  Now where would I find an API Token?  :)

**Comment by charlie-quinn** [comment]
You can find your Markbot API token here: https://progress.learn-the-web.algonquindesign.ca/profile/

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
